parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  variables:
    CPPTOOLS_DEV: 1

  steps:
  - task: NodeTool@0
    displayName: Use Node 8.x'
    inputs:
      versionSpec: 8.x

  - script: npm install
    displayName: "Install Dependencies"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'
      
  - script: npm run compile
    displayName: "Compile Sources"
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run pr-check
    displayName: 'Validate Extension/package.json'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run tslint
    displayName: 'Run Linter'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run unitTests
    displayName: 'Run Unit Tests'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'

  - script: npm run integrationTests
    displayName: 'Run Integration Tests'
    workingDirectory: '$(Build.SourcesDirectory)/Extension'
    env:
      MOCK_DEBUG: 1